kind: pipeline
name: default

steps:
- name: build
  image: golang:1.10.3
  commands:
  - mkdir -p /go/src/github.com/Amzani/product-api-first
  - cp -r . /go/src/github.com/Amzani/product-api-first/
  - ls /go/src/github.com/Amzani/product-api-first/
