kind: pipeline
name: default

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

steps:
- name: build
  image: docker:18.09.5-git
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - docker info
